error: Add smart errf function
This adds a new `errf` function that acts like a smarter version of
`fmt.Errorf` meant for chaining one or more long error messages.
Following the first printf-style string and its arguments, `errf` allows
zero or more printf-style strings and their arguments. These will be
concatenated together with `:` like so:

For example,

    fmt.Println(errf("foo", "bar", "baz"))
    // foo: bar: baz

    fmt.Println(errf("foo %d", 42, "bar %s", "baz"))
    // foo 42: bar baz

As a special case, the last such error can be an actual `error` object
instead of a printf-string.

    fmt.Println(errf("could not process %v", thing, err))
    // could not process Request{..}: great sadness

All such errors are separate error objects chained together with
`wrappedError` with the intention of separating them across multiple
lines in future changes.

Overall, this change loses some compile-time safety in favor of a more
ergonomic API for constructing large error chains.